### ISSUE TITLE
TypeError: Cannot read property 'syncWhenOpen' of undefined

### ISSUE THREAD

**Issue by binary64** [mkloubert/vs-deploy#118]
Hi I'm getting this error

```Cannot read property 'syncWhenOpen' of undefined: TypeError: Cannot read property 'syncWhenOpen' of undefined
    at Deployer.onDidOpenTextDocument (C:\Users\xx\.vscode\extensions\mkloubert.vs-deploy-10.0.0\out\src\deploy.js:2049:57)
    at e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:57853)
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:59575)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:361602
    at e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:57853)
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:59575)
    at e.$acceptDocumentsAndEditorsDelta (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:365689)
    at t.e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:444706)
    at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:290666)
    at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:290356)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:289383
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:291302
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:58570
    at e.invoke (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:57853)
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:59575)
    at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:107427)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)```

My settings.json:-

```{
    "deploy": {
        "packages": [
            {
                "name": "main",
                "description": "Package version 2.3.4",
                "files": [
                    "**/*.php",
                    "/*.json"
                ],
                "exclude": [
                    "tests/**"
                ],
                "deployOnSave": true,
                "syncWhenOpen": false,
                "noNodeModules": true
            }
        ],
        "targets": [
            {
                "type": "sftp",
                "name": "xxx.com",
                "description": "xxx.com",
                "host": "xxx.com",
                "port": 22,
                "user": "xxx",
                "password": "xxx",
                "checkBeforeDeploy": false,
                "dir": "/var/www/xxx",
                "mappings": [
                    {
                        "source": "/",
                        "target": "/"
                    }
                ]
            }
        ],
        "displayNetworkInfo": false,
        "displayLoadedPlugins": false,
        "alwaysShowPackageList": true,
        "alwaysShowTargetList": true
    },
    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": true
    }
}```

**Comment by mkloubert** [comment]
Maybe a similar problem like [here](https://github.com/mkloubert/vs-deploy/issues/115)?
